# Generated by Django 5.2.3 on 2025-06-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid_reader',
            name='port',
            field=models.CharField(max_length=100),
        ),
    ]
