# Generated by Django 5.2.3 on 2025-06-29 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0002_alter_rfid_reader_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('valid', 'valid'), ('incomplete', 'incomplete'), ('invalid', 'invalid')], max_length=10)),
                ('open_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='or_managements.operationsession')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
