# Generated by Django 5.2.3 on 2025-06-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0003_verificationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationsession',
            name='available_items',
            field=models.JSONField(blank=True, default=dict, help_text='Instruments and trays that were found but not used'),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='available_matches',
            field=models.JSONField(blank=True, default=dict, help_text='Available instruments/trays with same names as missing ones'),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='missing_items',
            field=models.JSONField(blank=True, default=dict, help_text='Required instruments and trays that were not found'),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='used_items',
            field=models.JSONField(blank=True, default=dict, help_text='Instruments and trays used in the operation'),
        ),
    ]
