# Generated by Django 5.2.3 on 2025-07-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0004_verificationsession_available_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='or_managements.rfidtag'),
        ),
    ]
