# Generated by Django 5.2.3 on 2025-07-03 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0005_tray_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tray',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('missing', 'Missing'), ('under_sterilization', 'Under Sterilization')], default='available', max_length=100),
        ),
        migrations.CreateModel(
            name='OutboundTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the outbound check was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_cleared', models.BooleanField(default=False, help_text='Whether all items were removed from room after operation')),
                ('remaining_items', models.JSONField(blank=True, default=dict, help_text='Items that remain in the room after operation')),
                ('extra_items', models.JSONField(blank=True, default=dict, help_text='Items found in the room that were not used in this operation')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the outbound check')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_checks', to='or_managements.operationsession')),
            ],
            options={
                'ordering': ['-check_time'],
            },
        ),
    ]
