# Generated by Django 5.2.3 on 2025-07-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0006_tray_status_outboundtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsession',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('outbound_cleared', 'Outbound Cleared'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50),
        ),
    ]
