# Generated by Django 5.2.3 on 2025-07-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0007_alter_operationsession_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationsession',
            old_name='available_items',
            new_name='available_items_dict',
        ),
        migrations.RenameField(
            model_name='verificationsession',
            old_name='missing_items',
            new_name='missing_items_dict',
        ),
        migrations.RenameField(
            model_name='verificationsession',
            old_name='used_items',
            new_name='used_items_dict',
        ),
        migrations.RemoveField(
            model_name='operationroom',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operationroom',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='operationsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operationsession',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='outboundtracking',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='verificationsession',
            name='available_matches',
        ),
        migrations.AddField(
            model_name='largeequipment',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='largeequipment',
            name='next_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='extra_items_dict',
            field=models.JSONField(blank=True, default=dict, help_text='Extra instruments and trays found in the room'),
        ),
        migrations.AddField(
            model_name='verificationsession',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('maintenance', 'Maintenance'), ('admin', 'Admin')], default='nurse', help_text='User role in the system', max_length=20),
        ),
        migrations.AlterField(
            model_name='verificationsession',
            name='state',
            field=models.CharField(choices=[('valid', 'valid'), ('incomplete', 'incomplete'), ('invalid', 'invalid'), ('failed', 'failed')], max_length=10),
        ),
    ]
