# Generated by Django 5.2.3 on 2025-07-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0008_rename_available_items_verificationsession_available_items_dict_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('in_use', 'In Use'), ('returned', 'Returned'), ('maintenance', 'Maintenance')], default='requested', max_length=50)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('maintenance_type', models.CharField(blank=True, max_length=50, null=True)),
                ('maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='or_managements.largeequipment')),
                ('operation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='or_managements.operationsession')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_out_time'],
                'indexes': [models.Index(fields=['equipment'], name='or_manageme_equipme_fd898e_idx'), models.Index(fields=['operation_session'], name='or_manageme_operati_4dd281_idx')],
            },
        ),
    ]
