# Generated by Django 5.2.3 on 2025-07-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0009_equipmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='largeequipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
