# Generated by Django 5.2.3 on 2025-07-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('or_managements', '0010_largeequipment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_use', 'In Use'), ('returned', 'Returned'), ('maintenance', 'Maintenance')], default='requested', max_length=50),
        ),
    ]
