# Generated by Django 5.2.3 on 2025-06-23 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned')], default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_instruments', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RFID_Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('last_scan_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['last_scan_time'],
            },
        ),
        migrations.CreateModel(
            name='Tray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_instruments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('operation_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='or_managements.operationroom')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='or_managements.operationtype')),
            ],
        ),
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=50)),
                ('last_detection_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_known_location', models.CharField(blank=True, max_length=100, null=True)),
                ('last_detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_tags', to='or_managements.rfid_reader')),
            ],
        ),
        migrations.CreateModel(
            name='LargeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_id', models.CharField(max_length=50, unique=True)),
                ('equipment_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('under_repair', 'Under Repair'), ('scheduled_maintenance', 'Scheduled Maintenance')], default='available', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('rfid_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='or_managements.rfidtag')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('missing', 'Missing'), ('under_sterilization', 'Under Sterilization')], max_length=100)),
                ('rfid_tag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag', to='or_managements.rfidtag')),
                ('tray', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='or_managements.tray')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('maintenance', 'Maintenance')], default='nurse', help_text='User role in the system', max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the user account', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
